### ISSUE TITLE
On the training of other captcha

### ISSUE THREAD

**Issue by ANewAnonymous** [symant233/zfsoft-captcha2#1]
Hello, author! If what I need to train is the new version of the square captcha, which has a total of 6 digits and a mixture of letters, how should I modify the code to train? Thank you very much for your reply!

**Comment by symant233** [comment]
Hi there. Cause no example picture been given, I could provide these suggestions:
1. download a considerable amount of random generated captcha code images, sign the output manually for training and testing.
2. Since it's 6 letters instead of 4, you should modify the picture split code (which splits one picture to four single letter pics at present) to adapt 6 letter scheme
3. change the model input size, perhaps numpy data structure too.

My memory of machine learning has been in headlong retreat. Anyway if there is a number(integer) in the code, then you stand to reconsider its value.

Hope this could help you.
